# Generated by Django 5.2.7 on 2025-10-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата оплаты"),
        ),
    ]
