# Generated by Django 5.2.7 on 2025-10-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(verbose_name="Дата оплаты"),
        ),
    ]
