# Generated by Django 5.2.7 on 2025-11-06 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_subscribe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscribe",
            old_name="subscribe_course",
            new_name="course",
        ),
    ]
