# Generated by Django 5.2.8 on 2025-11-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_payment_date_alter_payment_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(
                auto_created=True, blank=True, null=True, verbose_name="Дата оплаты"
            ),
        ),
    ]
