# Generated by Django 5.2.8 on 2025-11-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка сессии"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии"
            ),
        ),
    ]
