# Generated by Django 5.2.8 on 2025-11-09 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="link",
            new_name="session_link",
        ),
    ]
