# Generated by Django 5.2.8 on 2025-11-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_rename_link_payment_session_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="session_link",
            new_name="link",
        ),
    ]
