# Generated by Django 5.2.8 on 2025-11-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_rename_session_link_payment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Ссылка сессии"
            ),
        ),
    ]
