# Generated by Django 5.2.8 on 2025-11-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_payment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(
                auto_now_add=True, default="2024-01-01", verbose_name="Дата оплаты"
            ),
            preserve_default=False,
        ),
    ]
